force-app/main/default/objects/Account/recordTypes/Trainings_Provider.recordType-meta.xml
<RecordType>
    <fullName>Trainings_Provider</fullName>
    <active>true</active>
    <label>Trainings Provider</label>
</RecordType>

force-app/main/default/objects/Product2/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A Product from the &quot;Training&quot; Family must have as Provider an Account with &quot;Trainings Provider&quot; Record Type</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Trainings_Provider</value>
        </filterItems>
        <filterItems>
            <field>$Source.Family</field>
            <operation>equals</operation>
            <value>Training</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/classes/SendEventReminderSchedulableTest.cls
@isTest
public class SendEventReminderSchedulableTest {

    @isTest 
    static void createAnEventAndScheduleClassToRunNow() {
        Id trainingProviderRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Trainings_Provider').getRecordTypeId();
        Id attendeeRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Attendee').getRecordTypeId();
        Id trainingRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('Training').getRecordTypeId();

        Account trainingsProvider = new Account(
            Name = 'Test training provider',
            RecordTypeId = trainingProviderRecordTypeId
        );
        insert trainingsProvider;

        Product2 training = new Product2(
            Name = 'Test training',
            Start__c = Datetime.now().addHours(48).addMinutes(5),
            End__c = Datetime.now().addHours(48).addMinutes(10),
            Provider__c = trainingsProvider.Id,
            RecordTypeId = trainingRecordTypeId
        );
        insert training;

        Account attendee = new Account(
            LastName = 'Test attendee',
            PersonEmail = 'test.attendee@test.com',
            RecordTypeId = attendeeRecordTypeId
        );
        insert attendee;

        Asset asset = new Asset(
            Name = 'Test asset',
            Product2Id = training.Id,
            AccountId = attendee.Id
        );
        insert asset;

        Event trainingEvent = [
            SELECT Id 
            FROM Event 
            LIMIT 1
        ];

        Test.startTest();

        System.schedule('Test schedule class', '0 35 11 ? 6 3', new SendEventReminderSchedulable(trainingEvent.Id));
        
        Test.stopTest();
    }

}